---
- name: Configure docker environment
  no_log: true
  ansible.builtin.template:
    src: env.j2
    dest: /app/.env
    mode: u=rw,g=r,o=r
  vars:
    env:
      LOG_LEVEL: "{{ log_level }}"
      HTTP_ADDRESS: "https://node-{{ instance_id }}.{{ http_subdomain }}"
      DEBUG_ENABLED: "{{ debug_enabled }}"
      DDC_BUCKET_CONTRACT_API_URL: "{{ ddc_bucket_contract_url }}"
      DDC_BUCKET_CONTRACT_ACCOUNT_ID: "{{ ddc_bucket_contract_account_id }}"
      NODE_ID: "{{ instance_id | int + 1 }}"
      CLUSTER_ID: "{{ cluster_id }}"
      STORAGE: "{{ storage }}"
  notify: Restart Docker Compose

- name: Configure docker deployment
  ansible.builtin.set_fact:
    service_ports:
      - "5000:5000"
      - "8080:8080"
    service_volumes:
      - "{{ mnt_point }}/data:/data:rw"
      - "{{ mnt_point }}/config:/config:rw"
