---
- name: Check if sda is mounted
  ansible.builtin.stat:
    path: /dev/sda
  register: mounted

- name: Mount /dev/sda by following path /mnt/cere-data
  ansible.posix.mount:
    path: "{{ mnt_point }}"
    src: /dev/sda
    opts: defaults,nofail,discard
    state: mounted
    fstype: ext4
  when: mounted.stat.exists

- name: Git - Clone node installation repo
  ansible.builtin.git:
    repo: https://github.com/Cerebellum-Network/nodes-installation-scripts.git
    dest: /app/cere-network
    single_branch: yes
    version: master
    depth: 1
    force: yes

- name: Change directory permissions for cere-network/chain-data
  ansible.builtin.file:
    dest: /app/cere-network/chain-data
    owner: root
    group: root
    state: directory
    mode: u=rwX,g=rwX,o=rwX

- name: Create a symbolic link for cere-network
  ansible.builtin.file:
    src: /app/cere-network
    dest: /root/cere-network
    owner: root
    group: root
    state: link
    mode: u=rwX,g=rwX,o=rwX

- name: Change directory permissions for cere-data
  ansible.builtin.file:
    dest: "{{ mnt_point }}"
    owner: root
    group: root
    mode: u=rwX,g=rwX,o=rwX

- name: Create a symbolic link for cere-data
  ansible.builtin.file:
    src: "{{ mnt_point }}"
    dest: /root/cere-data
    owner: root
    group: root
    state: link
    mode: u=rwX,g=rwX,o=rwX

- name: Configure docker environment
  ansible.builtin.template:
    src: env.j2
    dest: /app/.env
    mode: u=rw,g=r,o=r
  vars:
    env:
      NODE_NAME: "{{ NODE_NAME }}"
      VERSION: "{{ VERSION }}"

      BOOT_NODE_IP_ADDRESS: "{{ BOOT_NODE_IP_ADDRESS }}"
      BOOT_NODE_IP_ADDRESS_2: "{{ BOOT_NODE_IP_ADDRESS_2 }}"
      NETWORK_IDENTIFIER: "{{ NETWORK_IDENTIFIER }}"
      NETWORK_IDENTIFIER_2: "{{ NETWORK_IDENTIFIER_2 }}"

      LOG_LEVEL: "{{ log_level }}"
      SPEC_PATH: "{{ SPEC_PATH }}"

      CUSTOM_PARAMETERS: "{{ CUSTOM_PARAMETERS }}"

- name: Configure docker deployment
  ansible.builtin.set_fact:
    service_ports:
      - "9944:9944"
      - "9933:9933"
      - "30333:30333"
      - "9615:9615"
    service_volumes:
      - "{{ mnt_point }}:/data:rw"
