---
- name: Git - Clone node installation repo
  ansible.builtin.git:
    repo: https://github.com/Cerebellum-Network/nodes-installation-scripts.git
    dest: /app/cere-network
    single_branch: true
    version: master
    force: true

- name: Change directory permissions for cere-network/chain-data
  ansible.builtin.file:
    dest: /app/cere-network/chain-data
    owner: root
    group: root
    state: directory
    mode: u=rwX,g=rwX,o=rwX

- name: Change directory permissions for cere-data
  ansible.builtin.file:
    dest: "{{ mnt_point }}"
    owner: root
    group: root
    mode: u=rwX,g=rwX,o=rwX

- name: Configure docker environment
  ansible.builtin.template:
    src: env.j2
    dest: /app/.env
    mode: u=rw,g=r,o=r
  vars:
    env:
      NODE_NAME: "{{ node_name }}"
      VERSION: "{{ version }}"

      BOOT_NODE_IP_ADDRESS: "{{ boot_node_ip_address }}"
      BOOT_NODE_IP_ADDRESS_2: "{{ boot_node_ip_address_2 }}"
      NETWORK_IDENTIFIER: "{{ network_identifier }}"
      NETWORK_IDENTIFIER_2: "{{ network_identifier_2 }}"

      LOG_LEVEL: "{{ log_level }}"
      SPEC_PATH: "{{ spec_path }}"

      CUSTOM_PARAMETERS: "{{ custom_parameters }}"

- name: Configure docker deployment
  ansible.builtin.set_fact:
    service_ports:
      - "9944:9944"
      - "8080:9933"
      - "30333:30333"
      - "9615:9615"
    service_volumes:
      - "/app/cere-network/spec-data:/cereio/spec-data:rw"
      - "{{ mnt_point }}:/data:rw"
    custom_command: "{{ lookup('ansible.builtin.template', 'command.sh.j2') }}"
