---
- name: Configure docker environment
  no_log: true
  ansible.builtin.template:
    src: env.j2
    dest: /app/.env
    mode: u=rw,g=r,o=r
  vars:
    env:
      LOG_LEVEL: "{{ log_level }}"
      HTTP_ADDRESS: "https://node-{{ instance_id }}.{{ http_subdomain }}"
      DEBUG_ENABLED: "{{ debug_enabled }}"

      BLOCKCHAIN_SECRET_PHRASE: "{{ ddc_mnemonic }}"

      BLOCKCHAIN_API_URL: "{{ blockchain_api_url }}"
      BLOCKCHAIN_DDC_BUCKET_CONTRACT: "{{ blockchain_ddc_bucket_contract }}"
      BLOCKCHAIN_ACTIVITY_CAPTURE_CONTRACT: "{{ blockchain_activity_capture_contract }}"
      NODE_SECRET_PHRASE: "{{ vars['node_secret_phrase_' + instance_id + '_' + location] }}"

      REDIS_URL: "{{ redis_url }}"
      REDIS_PASSWORD: "{{
        lookup(
          'community.hashi_vault.vault_kv2_get',
          environment_type + '/k8s/ddc-' + environment_type + '/dac-redis',
          url='https://vault.shared.aws.cere.io',
          auth_method='aws_iam',
          role_id='ansible',
          region='us-west-2',
          engine_mount_point='secret-network'
        )['secret']['REDIS_PASSWORD']
      }}"

      CLUSTER_ID: "{{ cluster_id }}"
      NODE_ID: "{{ NODE_ID | default(instance_id | int + 1) }}"
      SIZE: "{{ size }}"
      LOCATION: "{{ location }}"
  notify: Restart Docker Compose

- name: Configure docker deployment
  ansible.builtin.set_fact:
    service_ports:
      - "5000:5000"
      - "8080:8080"
    service_volumes:
      - "{{ mnt_point }}/data:/data:rw"
      - "{{ mnt_point }}/config:/config:rw"
