---
- name: Ensure that dependencies are installed
  ansible.builtin.apt:
    name:
      - debian-keyring
      - ca-certificates
      - debian-archive-keyring
      - apt-transport-https
      - gnupg2
      - curl
      - python3
      - python3-pip
      - python3-setuptools
      - tar
      - unzip
      - zip
    state: present
    update_cache: true

- name: Install Python Dependencies
  ansible.builtin.pip:
    name:
      - docker
#      - docker-compose
      - requests
      - setuptools
    executable: pip3

- name: Configure Hostname
  ansible.builtin.hostname:
    name: node-{{ instance_id }}.{{ http_subdomain }}
