---
- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable

- name: Install Docker with Compose App
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      # FIXME
      # - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true

- name: Start Docker system service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Create directory for project
  ansible.builtin.file:
    path: /app
    state: directory
    recurse: true
