---
- name: Install Docker with Compose App
  ansible.builtin.apt:
    name:
      - docker
      - docker-compose
    state: present

- name: Start Docker system service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Create directory for project
  ansible.builtin.file:
    path: /app
    state: directory
    recurse: true
