---
- name: Set ansible keys
  ansible.posix.authorized_key:
    user: root
    state: present
    key: |
      {{
        lookup(
          'community.hashi_vault.vault_kv2_get',
          'awx',
          url='https://vault.shared.aws.cere.io',
          auth_method='aws_iam',
          role_id='ansible',
          region='us-west-2',
          engine_mount_point='infra'
        )['secret']['ssh_legacy_public_key']
      }}
      {{
        lookup(
          'community.hashi_vault.vault_kv2_get',
          'awx',
          url='https://vault.shared.aws.cere.io',
          auth_method='aws_iam',
          role_id='ansible',
          region='us-west-2',
          engine_mount_point='infra'
        )['secret']['ssh_public_key']
      }}
