---
# tasks file for common

- name: Install Dependencies
  ansible.builtin.include_tasks:
    file: dependencies.yml

- name: Install Docker
  ansible.builtin.include_tasks:
    file: docker.yml

- name: Install Caddy
  ansible.builtin.include_tasks:
    file: caddy.yml
